apiVersion: v1
kind: Service
metadata:
  name: starbucks-recreate
  labels:
    app: starbucks-recreate
spec:
  selector:
    app: starbucks-recreate
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
